### ISSUE TITLE
被热修复的代码不能混淆吗

### ISSUE THREAD

**Issue by xiayifeng** [meili/Aceso#11]
我把demo中proguard-rules.pro中
#-keep class com.mogujie.aceso.demo.MainActivity {*;}
注释掉了，就不能被修复了。

**Comment by farmerjohngit** [comment]
@xiayifeng 支持混淆的，不过你需要保证在fix工程中编译时apply demo工程产生的mapping.即保证fix工程的混淆结果与demo工程一致。

**Comment by xiayifeng** [comment]
我直接-applymapping demo工程的mapping.txt报错，提示aceso-mapping.txt没有找到类

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> can not find class: com/mogujie/aceso/b , sure you aceso-mapping is right and this class not in blacklist.

**Comment by farmerjohngit** [comment]
@xiayifeng  已修复 #15

**Comment by 317764920** [comment]
宿主混淆了，fix工程报错了

Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinder depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$1 depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$1 depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$2 depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$2 depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFragment

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.322 secs
Please correct the above warnings first.

这貌似是butterknife的问题？

**Comment by farmerjohngit** [comment]
@317764920  看起来是dataBinding 和 混淆冲突了。不开aceso插件也会报错吧？

**Comment by 317764920** [comment]
@farmerjohngit 不会的呀，不开的话混淆后是可以编译通过的，开了之后debug下也是正常的

**Comment by farmerjohngit** [comment]
@317764920 麻烦提供更详细的log及其他信息 。参考 https://github.com/meili/Aceso/wiki/Issue-Format

**Comment by 317764920** [comment]
@farmerjohngit 
异常类型：fix工程编译异常

手机型号：

手机系统版本：

aceso-build插件版本：0.0.2

aceso-android-lib插件版本：0.0.1

android gradle插件版本：2.2.3

gradle版本：2.14.1

系统：Windows 10

堆栈：

Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinder depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFra
gment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFr
agment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding depends on program class com.cqxiaokang.cloudloan.fragment.index.HomeFr
agment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$1 depends on program class com.cqxiaokang.cloudloan.fragment.index.Home
Fragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$1 depends on program class com.cqxiaokang.cloudloan.fragment.index.Home
Fragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$2 depends on program class com.cqxiaokang.cloudloan.fragment.index.Home
Fragment
Warning: library class com.cqxiaokang.cloudloan.fragment.index.HomeFragment_ViewBinding$2 depends on program class com.cqxiaokang.cloudloan.fragment.index.Home
Fragment
......
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: Job failed, see logs for details
        at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:196)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245
)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: java.io.IOException: Please correct the above warnings first.
        at proguard.Initializer.execute(Initializer.java:473)
        at proguard.ProGuard.initialize(ProGuard.java:233)
        at proguard.ProGuard.execute(ProGuard.java:98)
        at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:54)
        at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:254)
        at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:63)
        at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:173)
        at com.android.builder.tasks.Job.runTask(Job.java:49)
        at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:223)

**Comment by farmerjohngit** [comment]
@317764920 看不出问题， 方不方便给一个出错的demo工程？

**Comment by 317764920** [comment]
@farmerjohngit demo工程入口：https://github.com/317764920/Aceso-test

**Comment by farmerjohngit** [comment]
@31  你的demo工程并没有报你所说的错误。报的是：
the method : init.()V in class : com/mogujie/aceso/demo/MainActivity not found in the aceso-mapping.
   sure you aceso-mapping is right and no new method.

在fix工程中apply demo的mapping文件就好了。见wiki Aceso修复流程

**Comment by 317764920** [comment]
@farmerjohngit 
acesoMapping文件的路径我已经指定到了demo生成的aceso目录下了啊

**Comment by 317764920** [comment]
@farmerjohngit demo下载下来没有改过gradle里面aceso的配置
还是这个路径
def getAcesoMapping() {
    return project.rootProject.file("../aceso-demo/app/build/intermediates/aceso/aceso-mapping/full/${buildTypeStr()}/aceso-mapping.txt").absolutePath
}

**Comment by 317764920** [comment]
@farmerjohngit 我把mapping文件拷出来换了个路径试了一下，还是这个问题，apply demo的mapping文件应该是正确的
看了一下init.()V in class : com/mogujie/aceso/demo/MainActivity在mapping文件中确实找不到

**Comment by farmerjohngit** [comment]
@317764920 我说的是proguard的mapping 。不是aceso的mapping

**Comment by xiayifeng** [comment]
new Aceso().installPatch(optDir, patchFile);修复方法会卡住主线程吗，需要放到子线程去做吗？

**Comment by farmerjohngit** [comment]
@xiayifeng  installPatch是阻塞方法。具体要放在哪个线程根据具体场景而定
