### ISSUE TITLE
不能插桩带JSR/RET指令的类

### ISSUE THREAD

**Issue by cryforyou** [meili/Aceso#2]
Caused by: java.lang.RuntimeException: JSR/RET are not supported with computeFrames option
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.MethodWriter.visitJumpInsn(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitJumpInsn(Unknown Source)
        at org.objectweb.asm.tree.JumpInsnNode.accept(Unknown Source)
        at org.objectweb.asm.tree.InsnList.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at com.mogujie.instantrun.IncrementalSupportVisitor.visitMethod(IncrementalSupportVisitor.java:146)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
        at com.mogujie.instantrun.IncrementalVisitor.instrumentClass(IncrementalVisitor.java:292)
        at com.mogujie.instantrun.IncrementalVisitor$instrumentClass.call(Unknown Source)
        at com.mogujie.aceso.HookWrapper.processClassInternal(HookWrapper.groovy:224)
        at com.mogujie.aceso.HookWrapper.instrumentOneEntry(HookWrapper.groovy:170)
        at com.mogujie.aceso.HookWrapper$_inject_closure2.doCall(HookWrapper.groovy:145)
        at com.mogujie.aceso.HookWrapper.inject(HookWrapper.groovy:140)
        at com.mogujie.aceso.HookWrapper$inject$0.callStatic(Unknown Source)
        at com.mogujie.aceso.HookWrapper.instrument(HookWrapper.groovy:85)
        at com.mogujie.aceso.HookWrapper$instrument.call(Unknown Source)

**Comment by farmerjohngit** [comment]
@cryforyou 这个问题一般出现在一些第3方包上。目前的解决方法是把报错的类放入到黑名单中。
操作如下：
设置build.gradle中Aceso的日志等级：logLevel=3，然后在报错堆栈的上方看到类似IncrementalSupportVisitor: Visiting 类路径 的log，然后把这个类放入到黑名单中。

**Comment by 317764920** [comment]
已解决 ，感谢aceso的开发人员的解答

**Comment by Dawnton** [comment]
第三方jar包中的类很多,为什么加了--blackListPath = "aceso-blacklist.txt"话也还是会报这个错呢?
aceso-blacklist.txt中的配置如下:

com/loopj/android/http/
org/apache/commons/codec/
org/apache/commons/codec/binary/
org/apache/commons/codec/digest/
org/apache/commons/codec/language/
org/apache/commons/codec/language/bm/
org/apache/commons/codec/net/

com/google/gson/
com/google/gson/annotations/
com/google/gson/internal/
com/google/gson/internal/bind/
com/google/gson/internal/bind/util/
com/google/gson/reflect/
com/google/gson/stream/

**Comment by zlg2338781286** [comment]
能看到很多IncrementalSupportVisitor: Visiting 这种的类，黑名单是在哪里，怎么放

**Comment by 317764920** [comment]
@zlg2338781286 
![qq 20170228152256](https://cloud.githubusercontent.com/assets/17998140/23395507/f395d0b4-fdc9-11e6-90c1-b064268c04f4.png)

**Comment by Dawnton** [comment]
@317764920 @farmerjohngit 在gradle文件中是怎么配置的,为什么我在配置过--blackListPath = "./aceso-blacklist.txt" 后还是会报这个错,相应的包名也加进来了

**Comment by 317764920** [comment]
@Dawnton 看demo

**Comment by Dawnton** [comment]
@317764920 Demo里面没有关于黑名单设置的啊

**Comment by 317764920** [comment]
@Dawnton gradle的配置参照demo中host和fix工程

**Comment by Dawnton** [comment]
@317764920 非常感谢

**Comment by zlg2338781286** [comment]
@317764920 gradle的配置参照demo中host和fix工程？在demo中没找到呀
有qq群吗

**Comment by zlg2338781286** [comment]
@317764920 意思是黑名单这个文件直接创建在app下面就好了是吗

**Comment by farmerjohngit** [comment]
@zlg2338781286 见wiki: https://github.com/meili/Aceso/wiki blacklist项

**Comment by zlg2338781286** [comment]
嗯，谢谢

**Comment by xiejinsorry** [comment]
@farmerjohngit  能否加个好友 指点一下？ 我这里还是有问题啊？ 2933513182
