### ISSUE TITLE
android 8.0.0 修复失败

### ISSUE THREAD

**Issue by beilo** [meili/Aceso#48]
机型: 华为P9 Plus || android studio 模拟器 28版本
案例: 就是aceso-demo,没有改动过
error:
```
E/Aceso: Failed to install patch. 
         java.lang.ClassNotFoundException: com.android.tools.fd.runtime.AppPatchesLoaderImpl
             at java.lang.Class.classForName(Native Method)
             at java.lang.Class.forName(Class.java:453)
             at com.mogujie.aceso.Aceso.installPatch(Aceso.java:51)
             at com.mogujie.aceso.demo.MainActivity.fix(MainActivity.java:47)
             at java.lang.reflect.Method.invoke(Native Method)
             at android.view.View$DeclaredOnClickListener.onClick(View.java:5363)
             at android.view.View.performClick(View.java:6291)
             at android.view.View$PerformClick.run(View.java:24931)
             at android.os.Handler.handleCallback(Handler.java:808)
             at android.os.Handler.dispatchMessage(Handler.java:101)
             at android.os.Looper.loop(Looper.java:166)
             at android.app.ActivityThread.main(ActivityThread.java:7425)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.AppPatchesLoaderImpl" on path: DexPathList[[zip file "/storage/emulated/0/fix.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /product/lib64]]
             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
             at java.lang.Class.classForName(Native Method) 
             at java.lang.Class.forName(Class.java:453) 
             at com.mogujie.aceso.Aceso.installPatch(Aceso.java:51) 
             at com.mogujie.aceso.demo.MainActivity.fix(MainActivity.java:47) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at android.view.View$DeclaredOnClickListener.onClick(View.java:5363) 
             at android.view.View.performClick(View.java:6291) 
             at android.view.View$PerformClick.run(View.java:24931) 
             at android.os.Handler.handleCallback(Handler.java:808) 
             at android.os.Handler.dispatchMessage(Handler.java:101) 
             at android.os.Looper.loop(Looper.java:166) 
             at android.app.ActivityThread.main(ActivityThread.java:7425) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
         	Suppressed: java.io.IOException: No original dex files found for dex location /storage/emulated/0/fix.apk
             at dalvik.system.DexFile.openDexFileNative(Native Method)
             at dalvik.system.DexFile.openDexFile(DexFile.java:353)
             at dalvik.system.DexFile.<init>(DexFile.java:100)
             at dalvik.system.DexFile.<init>(DexFile.java:74)
             at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
             at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
             at dalvik.system.DexPathList.<init>(DexPathList.java:157)
             at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
             at com.android.tools.fd.runtime.InstantRunClassLoader.<init>(InstantRunClassLoader.java:32)
             at com.mogujie.aceso.Aceso.installPatch(Aceso.java:49)
             		... 12 more
```

**Comment by beilo** [comment]
emmmmm,我错了 我改了targetSdkVersion 到26了,没有获取动态权限.  8.0上demo运行是正常的.不好意思.
